redis_uri = "redis://127.0.0.1:6379"

[application]
port = 8000

[database]
host = "127.0.0.1"
port = 5432
username = "postgres"
password = "password"
database_name = "newsletter"

[email_client]
sender_email = "test@gmail.com"
smtp_relay = "smtp.gmail.com"
smtp_username = "test@gmail.com"
smtp_password = "secret password"
